### ISSUE TITLE
JSON library incompatible with Android

### ISSUE THREAD

**Issue by marcnause** [loklak/loklak_jlib_api#1]
loklakj_lib uses the json.org JSON library. Android also uses json.org: [https://developer.android.com/reference/org/json/package-summary.html](https://developer.android.com/reference/org/json/package-summary.html) 

Unfortunately both versions are not compatible. The version used in loklakj_lib knows JSONObject.put(String, Collection) which is used in org.loklak.objects.MessageEntry for example. The version contained in Android does not know this method.

This seems to be the reason for the Android-Wok not being able to push data at the moment:

`failed synchronous push to backend, attempt 4
                                                                    java.lang.NoSuchMethodError: org.json.JSONObject.put
                                                                        at org.loklak.objects.MessageEntry.toJSON(Unknown Source)
                                                                        at org.loklak.objects.Timeline.toJSON(Unknown Source)
                                                                        at org.loklak.client.PushClient.push(Unknown Source)
                                                                        at org.loklak.android.wok.Harvester$PushThread.doInBackground(Harvester.java:263)
                                                                        at org.loklak.android.wok.Harvester$PushThread.doInBackground(Harvester.java:244)
                                                                        at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                        at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                        at java.lang.Thread.run(Thread.java:841)`

Unfortunately I think the only solution is to replace json.org.

**Comment by marcnause** [comment]
Thinking about it again, I think it should be possible to keep json.org in the project and write a workaround for Android. I'll try to come up with a solution ASAP and will create a pull request when I'm done.

**Comment by marcnause** [comment]
Pull request: [https://github.com/loklak/loklakj_lib/pull/2](https://github.com/loklak/loklakj_lib/pull/2)

**Comment by sudheesh001** [comment]
@Low012 Merged it , Is the server issue fixed too with this change ? https://github.com/loklak/loklak_server/issues/544

**Comment by marcnause** [comment]
The "HTTP code 504"-issue is a separate issue which I encountered both on an Android device running [Loklak Wok for Android](https://github.com/loklak/loklak_wok_android/) and on my Laptop running [Loklak Wok for desktop](https://github.com/loklak/loklak_wok_desktop).

This issue prevented POSTing messages to the backend since it already crashed when the JSON.
